/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package internet.mangement.system;

import DAO.PlanDAO;
import Model.Plan;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoang
 */
public class PlanManagement extends javax.swing.JFrame {

    /**
     * Creates new form Plan
     */
    public PlanManagement() {
        initComponents();
//        setupTableSelectionListener();

        try{
            List<Plan> plans = PlanDAO.getAll();
            for (Plan plan : plans){
                System.out.println(plan.getPlan_id() + " - ");
            }
        }catch(Exception e){
        e.printStackTrace();
        }
           
        
        DefaultTableModel model = (DefaultTableModel) plan_table.getModel();
        model.setRowCount(0); // Xoá dữ liệu cũ nếu có
        try{
            List<Plan> list = PlanDAO.getAll();
            System.out.println("So goi cuoc " + list.size());
            // for (Plan pl : list){
            //     Object[] row = {
            //         pl.getPlan_id(),
            //         pl.getName(),
            //         pl.getPrice(),
            //         pl.getMax_speed_domestic(),
            //         pl.getMin_speed_domestic(),
            //         pl.getMax_speed_international(),
            //         pl.getMin_speed_international(),
            //     };
            //     model.addRow(row);
            // }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel_SearchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel_BwFilterPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSlider_internationalMin = new javax.swing.JSlider();
        jSlider_internationalMax = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Dimension d = new Dimension(68, 26);
        txt_dom_min = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dom_max = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_inter_max = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_inter_min = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jSlider_domesticMax = new javax.swing.JSlider();
        jSlider_domesticMin = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_PriceFilterPanel = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSlider_priceMin = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        jSlider_priceMax = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_price_max = new javax.swing.JTextField();
        txt_price_min = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        plan_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel_SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel1.setText("Tìm kiếm gói cước:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel_BwFilterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Tốc độ tối thiểu quốc tế:");

        jSlider_internationalMin.setMaximum(1000);
        jSlider_internationalMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_internationalMinStateChanged(evt);
            }
        });

        jSlider_internationalMax.setMaximum(1000);
        jSlider_internationalMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_internationalMaxStateChanged(evt);
            }
        });

        jLabel4.setText("Tốc độ tối đa quốc tế:");

        jCheckBox1.setText("Lọc theo tốc độ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tốc độ trong nước:");

        txt_dom_min.setMinimumSize(d);
        txt_dom_min.setPreferredSize(d);
        txt_dom_min.setMaximumSize(d);
        txt_dom_min.setText("0");
        txt_dom_min.setName(""); // NOI18N
        txt_dom_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dom_minActionPerformed(evt);
            }
        });

        jLabel7.setText("-");

        txt_dom_max.setMinimumSize(d);
        txt_dom_max.setPreferredSize(d);
        txt_dom_max.setMaximumSize(d);
        txt_dom_max.setText("0");
        txt_dom_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dom_maxActionPerformed(evt);
            }
        });

        jLabel8.setText("Tốc độ quốc tế:");

        txt_inter_max.setMinimumSize(d);
        txt_inter_max.setPreferredSize(d);
        txt_inter_max.setMaximumSize(d);
        txt_inter_max.setText("0");

        jLabel9.setText("-");

        txt_inter_min.setMinimumSize(d);
        txt_inter_min.setPreferredSize(d);
        txt_inter_min.setMaximumSize(d);
        txt_inter_min.setText("0");

        jSlider_domesticMax.setMaximum(1000);
        jSlider_domesticMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_domesticMaxStateChanged(evt);
            }
        });

        jSlider_domesticMin.setMaximum(1000);
        jSlider_domesticMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_domesticMinStateChanged(evt);
            }
        });

        jLabel3.setText("Tốc độ tối thiểu trong nước:");

        jLabel2.setText("Tốc độ tối đa trong nước:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider_domesticMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider_domesticMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_domesticMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_domesticMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_BwFilterPanelLayout = new javax.swing.GroupLayout(jPanel_BwFilterPanel);
        jPanel_BwFilterPanel.setLayout(jPanel_BwFilterPanelLayout);
        jPanel_BwFilterPanelLayout.setHorizontalGroup(
            jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BwFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BwFilterPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BwFilterPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_internationalMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSlider_internationalMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_BwFilterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_dom_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_dom_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BwFilterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_inter_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_inter_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_BwFilterPanelLayout.setVerticalGroup(
            jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BwFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_dom_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_dom_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_internationalMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_internationalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BwFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_inter_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_inter_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel_PriceFilterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBox2.setText(" Lọc theo giá cước");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Giá cước:");

        jLabel14.setText("Giá cước tối đa:");

        jLabel15.setText("Giá cước tối thiểu:");

        jLabel17.setText("-");

        txt_price_max.setMinimumSize(d);
        txt_price_max.setPreferredSize(d);
        txt_price_max.setMaximumSize(d);
        txt_price_max.setText("0");

        txt_price_min.setMinimumSize(d);
        txt_price_min.setPreferredSize(d);
        txt_price_min.setMaximumSize(d);
        txt_price_min.setText("0");

        javax.swing.GroupLayout jPanel_PriceFilterPanelLayout = new javax.swing.GroupLayout(jPanel_PriceFilterPanel);
        jPanel_PriceFilterPanel.setLayout(jPanel_PriceFilterPanelLayout);
        jPanel_PriceFilterPanelLayout.setHorizontalGroup(
            jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PriceFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PriceFilterPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PriceFilterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PriceFilterPanelLayout.createSequentialGroup()
                                .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSlider_priceMax, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                    .addComponent(jSlider_priceMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PriceFilterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_price_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(txt_price_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_PriceFilterPanelLayout.createSequentialGroup()
                    .addContainerGap(443, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(80, 80, 80)))
        );
        jPanel_PriceFilterPanelLayout.setVerticalGroup(
            jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PriceFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_priceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_priceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_price_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_price_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel_PriceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_PriceFilterPanelLayout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addContainerGap()))
        );

        jButton2.setText("Lọc");

        javax.swing.GroupLayout jPanel_SearchPanelLayout = new javax.swing.GroupLayout(jPanel_SearchPanel);
        jPanel_SearchPanel.setLayout(jPanel_SearchPanelLayout);
        jPanel_SearchPanelLayout.setHorizontalGroup(
            jPanel_SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SearchPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_BwFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_PriceFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel_SearchPanelLayout.setVerticalGroup(
            jPanel_SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel_BwFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_PriceFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_SearchPanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách gói cước"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        plan_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên gói", "Giá gói", "Tốc độ tối đa trong nước", "Tốc độ tối thiểu trong nước", "Tốc độ tối đa quốc tế", "Tốc độ tối thiểu quốc tế"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(plan_table);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setupTableSelectionListener() {
            DefaultTableModel model = (DefaultTableModel) plan_table.getModel();
        model.setRowCount(0); // Xoá dữ liệu cũ nếu có
        try{
                List<Plan> ds = PlanDAO.getAll();
            for (Plan pl : ds){
                Object[] row = {
                    pl.getPlan_id(),
                    pl.getName(),
                    pl.getPrice(),
                    pl.getMax_speed_domestic(),
                    pl.getMin_speed_domestic(),
                    pl.getMax_speed_international(),
                    pl.getMin_speed_international(),
                };
                model.addRow(row);
            }
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e, "Message", JOptionPane.ERROR_MESSAGE);
}
        
//        plan_table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
//            @Override
//            public Component getTableCellRendererComponent(JTable table, Object value,
//                                                           boolean isSelected, boolean hasFocus, int row, int column) {
//
//                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
//
//                if (!isSelected) {
//                    if (row % 2 != 0) {
//                        c.setBackground(Color.WHITE);
//                    } else {
//                        c.setBackground(new Color(240, 240, 240));
//                    }
//                    c.setForeground(Color.BLACK);
//                } else {
//                    c.setBackground(table.getSelectionBackground());
//                    c.setForeground(table.getSelectionForeground());
//                }
//
//                return c;
//            }
//        });
//
//        txtUserId.setEditable(false);
//        txtUserName.setEditable(false);
//        txtPassword.setEditable(false);
//        txtCreateAt.setEditable(false);
//        txtStatus.setEditable(false);
//        cmbRole2.setEnabled(false);
//
//        tblUser.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
//            if (!e.getValueIsAdjusting()) {
//                int selectedRow = tblUser.getSelectedRow();
//                if (selectedRow != -1) {
//                    displaySelectedUserDetails(selectedRow);
//                }
//            }
//        });
//        });
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jSlider_domesticMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_domesticMaxStateChanged
        // TODO add your handling code here:
        int max = jSlider_domesticMax.getValue();
        int min = jSlider_domesticMin.getValue();
        if (min > max){
            min = max;
            jSlider_domesticMin.setValue(min);
            
        }
        txt_dom_max.setText(String.valueOf(max));
//        jSlider_domesticMax.updateUI();
        
    }//GEN-LAST:event_jSlider_domesticMaxStateChanged

    private void jSlider_domesticMinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_domesticMinStateChanged
        // TODO add your handling code here
        int max = jSlider_domesticMax.getValue();
        int min = jSlider_domesticMin.getValue();
        if (max < min){
            max = min;
            jSlider_domesticMax.setValue(max);
            
        }
        txt_dom_min.setText(String.valueOf(min));
//        jSlider_domesticMin.updateUI();
    }//GEN-LAST:event_jSlider_domesticMinStateChanged

    private void jSlider_internationalMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_internationalMaxStateChanged
        // TODO add your handling code here:
        int max = jSlider_internationalMax.getValue();
        int min = jSlider_internationalMin.getValue();
        if (min > max){
            min = max;
            jSlider_internationalMin.setValue(min);
            
        }
        txt_inter_max.setText(String.valueOf(max));
//        jSlider_internationalMax.updateUI();
    }//GEN-LAST:event_jSlider_internationalMaxStateChanged

    private void jSlider_internationalMinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_internationalMinStateChanged
        // TODO add your handling code here:
        int max = jSlider_internationalMax.getValue();
        int min = jSlider_internationalMin.getValue();
        if (max < min){
            max = min;
            jSlider_internationalMax.setValue(max);
            
        }
        txt_inter_min.setText(String.valueOf(min));
//        jSlider_internationalMin.updateUI();
    }//GEN-LAST:event_jSlider_internationalMinStateChanged

    private void txt_dom_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dom_minActionPerformed
        // TODO add your handling code here:
        try{
            int value = Integer.parseInt(txt_dom_min.getText());
            value = Math.max(jSlider_domesticMin.getMinimum(), Math.min(value, jSlider_domesticMax.getValue()));
            jSlider_domesticMin.setValue(value);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho tốc độ tối thiểu!");
}
    }//GEN-LAST:event_txt_dom_minActionPerformed

    private void txt_dom_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dom_maxActionPerformed
        // TODO add your handling code here:
        try {
            int value = Integer.parseInt(txt_dom_max.getText());
            value = Math.min(jSlider_domesticMax.getMaximum(), Math.max(value, jSlider_domesticMin.getValue()));
            jSlider_domesticMax.setValue(value);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho tốc độ tối đa!");
        }
    }//GEN-LAST:event_txt_dom_maxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanManagement().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_BwFilterPanel;
    private javax.swing.JPanel jPanel_PriceFilterPanel;
    private javax.swing.JPanel jPanel_SearchPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider_domesticMax;
    private javax.swing.JSlider jSlider_domesticMin;
    private javax.swing.JSlider jSlider_internationalMax;
    private javax.swing.JSlider jSlider_internationalMin;
    private javax.swing.JSlider jSlider_priceMax;
    private javax.swing.JSlider jSlider_priceMin;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable plan_table;
    private javax.swing.JTextField txt_dom_max;
    private javax.swing.JTextField txt_dom_min;
    private javax.swing.JTextField txt_inter_max;
    private javax.swing.JTextField txt_inter_min;
    private javax.swing.JTextField txt_price_max;
    private javax.swing.JTextField txt_price_min;
    // End of variables declaration//GEN-END:variables

}
